Add builder for additional header values
snapview/tungstenite-rs pull request #400
Opened 2024-01-10 09:32 UTC by ManevilleF

## Work done

Added a `ClientRequestBuilder` type inspired by [websockets](https://docs.rs/websockets/latest/websockets/struct.WebSocketBuilder.html) to allow for additional header values in the request, like authorization or subprotocols.

The way I implemented this is not the cleanest but I wanted to avoid any breaking change.

This is merely a proposal, so feedback welcome !

2024-01-19 23:21 UTC, Its-Just-Nans commented
This would be great to simulate a connection from a browser

- <https://datatracker.ietf.org/doc/html/rfc6455>

```text
8.   The request MUST include a header field with the name |Origin|
        [[RFC6454](https://datatracker.ietf.org/doc/html/rfc6454)] if the request is coming from a browser client.  If
        the connection is from a non-browser client, the request MAY
        include this header field if the semantics of that client match
        the use-case described here for browser clients.  The value of
        this header field is the ASCII serialization of origin of the
        context in which the code establishing the connection is
        running.  See [[RFC6454](https://datatracker.ietf.org/doc/html/rfc6454)] for the details of how this header field
        value is constructed.
```

2024-01-25 18:37 UTC, daniel-abramov requested changes
NB: These changes might indeed be useful, but the CI pipeline fails. I also think writing a couple of tests for the subprotocol functionality would be useful.

2024-02-02 10:21 UTC, Its-Just-Nans commented
@ManevilleF  I'v made PR once again on your repo to correct doc (once again 😅) and add a test

Link to the PR: https://github.com/ManevilleF/tungstenite-rs/pull/2

Maybe after you merged it @daniel-abramov could merge this one!

2024-02-05 16:53 UTC, daniel-abramov commented
Nice. Btw, one of the CI steps fails. I did not check it in a detail, but my first guess is that the new example [might require enabling some features](https://github.com/snapview/tungstenite-rs/blob/master/Cargo.toml#L78).

2024-02-05 19:07 UTC, Its-Just-Nans commented
@ManevilleF  If you add
```
#![cfg(feature = "handshake")]
```
at the top of [the test file](https://github.com/ManevilleF/tungstenite-rs/blob/4e88b43f93aed436f2e1057aaf49a676c4016822/tests/client_headers.rs#L1)

I guess it should work ?

2024-02-12 19:55 UTC, daniel-abramov approved these changes

2024-02-12 19:56 UTC, merged