Make url as feature and bump version
snapview/tungstenite-rs pull request #419
Opened 2024-04-21 20:43 UTC by Its-Just-Nans

Hello,

This PR fixes:

- https://github.com/snapview/tungstenite-rs/issues/412
- https://github.com/snapview/tungstenite-rs/issues/409

2024-04-23 14:44 UTC, daniel-abramov reviewed
Looks good. One question though: why is the newly introduced `tests/url_feature.rs` is a copy-paste of the existing test (with the only single exception of using `Url`)? - I think this might be a bit confusing.

2024-04-23 16:08 UTC, Its-Just-Nans commented
Yes.
I changed the test. Is that better ?

Thanks

2024-04-25 19:58 UTC, daniel-abramov requested changes
Looks good!

Just to clarify one thing: if I got your intentions right, you want us to publish a new version after merging this PR, right? (otherwise CHANGELOG should contain `Unreleased` instead of `0.22.0` and also the update in the `Cargo.toml` would also not be necessary).

AFAIR originally we wanted to first wait for https://github.com/snapview/tungstenite-rs/pull/363 first and then release a version. But if a builder pattern is useful on its own, we could make a release before #363 I think.

2024-04-25 19:58 UTC, daniel-abramov commented on CHANGELOG.md
> +- Add Header and subprotocol support at creation
```suggestion
- Make `url` optional.
- Add a builder for convenient headers and subprotocols construction.
```

2024-04-25 19:58 UTC, daniel-abramov commented on Cargo.toml
>  documentation = "https://docs.rs/tungstenite/0.21.0"
```suggestion
documentation = "https://docs.rs/tungstenite/0.22.0"
```

If the version is raised, we must also update the documentation link.

2024-04-25 20:08 UTC, Its-Just-Nans commented
> Looks good!
> 
> Just to clarify one thing: if I got your intentions right, you want us to publish a new version after merging this PR, right? (otherwise CHANGELOG should contain `Unreleased` instead of `0.22.0` and also the update in the `Cargo.toml` would also not be necessary).
> 
> AFAIR originally we wanted to first wait for #363 first and then release a version. But if a builder pattern is useful on its own, we could make a release before #363 I think.

Yes, make a release version is my goal. With a new version I could (update and) merge https://github.com/rerun-io/ewebsock/pull/27 crate which is using tungstenite

For #363 I think @conorbros is a little busy at the moment because I sent him a PR (https://github.com/shotover/tungstenite-rs/pull/1) but he didn't accept it for now

A solution could be to merge https://github.com/Its-Just-Nans/tungstenite-rs/tree/master directly into tungstenite (without passing by the fork of @conorbros). But that would make @conorbros invalid his PR. I don't know if it's a good and acceptable way of doing it

2024-04-26 07:42 UTC, Its-Just-Nans commented
I think #363 may be mergeable now (thank you @conorbros) !

So maybe we can merge #363 then this one ?

2024-05-08 17:59 UTC, daniel-abramov commented
That makes sense. I think we could merge #363; it just requires minor updates to pass the CI.

2024-05-13 19:57 UTC, merged